# Generated by Django 4.1.7 on 2023-03-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="phone_number",
            field=models.CharField(default=9738273829, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="zipcode",
            field=models.CharField(max_length=5),
        ),
    ]
