# Generated by Django 4.1.7 on 2023-02-27 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('portion_size', models.FloatField()),
                ('serving_recommendation', models.CharField(max_length=100)),
                ('caleories_per_portion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PetHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('temperature_latest', models.FloatField()),
                ('temperature_avg', models.FloatField()),
                ('last_checkup_date', models.DateField()),
                ('next_checkup_date', models.DateField()),
                ('diet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.diet')),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Treat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('portion_size', models.CharField(max_length=100)),
                ('caleories_per_portion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TreatServing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateTimeField(auto_now_add=True)),
                ('number_of_portions', models.IntegerField()),
                ('pet_health', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pethealth')),
                ('treat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.treat')),
            ],
        ),
        migrations.CreateModel(
            name='FoodServing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateTimeField(auto_now_add=True)),
                ('number_of_portions', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.food')),
                ('pet_health', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pethealth')),
            ],
        ),
        migrations.AddField(
            model_name='diet',
            name='food',
            field=models.ManyToManyField(related_name='diets', to='pets.food'),
        ),
        migrations.AddField(
            model_name='diet',
            name='treats',
            field=models.ManyToManyField(related_name='diets', to='pets.treat'),
        ),
    ]
