# Generated by Django 4.1.7 on 2023-02-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='name',
            field=models.CharField(default='DIET1', max_length=50),
            preserve_default=False,
        ),
    ]
