# Generated by Django 4.1.7 on 2023-02-27 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_diet_food_pethealth_treat_treatserving_foodserving_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pethealth',
            name='temperature_avg',
        ),
    ]
