# Generated by Django 4.1.7 on 2023-03-11 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0003_foodserving_pet_treatserving_pet"),
    ]

    operations = [
        migrations.CreateModel(
            name="BehavioralQuirks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FoodAllergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Medications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="pethealth",
            name="temperature_latest",
        ),
        migrations.AddField(
            model_name="pethealth",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="pethealth",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="pethealth",
            name="medical_history",
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pethealth",
            name="special_instructions",
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Veterinarian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clinic_name", models.CharField(max_length=100)),
                ("address_street", models.CharField(max_length=100)),
                ("address_city", models.CharField(max_length=100)),
                ("address_state", models.CharField(max_length=100)),
                ("address_zipcode", models.CharField(max_length=10)),
                ("phone_number", models.CharField(max_length=20)),
                ("email_address", models.EmailField(max_length=254)),
                ("website_url", models.URLField()),
                ("veterinarian_names", models.CharField(max_length=100)),
                ("authorized", models.BooleanField(default=False)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veterinarian",
                        to="pets.pet",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pethealth",
            name="behavioral_quirks",
            field=models.ManyToManyField(blank=True, to="pets.behavioralquirks"),
        ),
        migrations.AddField(
            model_name="pethealth",
            name="food_allergies",
            field=models.ManyToManyField(blank=True, to="pets.foodallergy"),
        ),
        migrations.AddField(
            model_name="pethealth",
            name="medications",
            field=models.ManyToManyField(blank=True, to="pets.medications"),
        ),
    ]
