# Generated by Django 4.1.7 on 2023-03-11 02:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0004_behavioralquirks_foodallergy_medications_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PetDailyDiet",
        ),
    ]
