# Generated by Django 4.1.7 on 2023-03-11 02:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0005_delete_petdailydiet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pethealth",
            name="diet",
        ),
        migrations.DeleteModel(
            name="Diet",
        ),
    ]
